### ISSUE TITLE
Peer Feedback

### ISSUE THREAD

**Issue by ninoschelcher** [max-hauser/frontend-data#1]
**Repository:**

- [x] Livedemo bestaat, zou ik misschien nog wel in de sidebar zetten zodat je niet de readme in hoeft.
- [x]  Misschien in de beschrijven meer toevoegen over dat je nu een interactieve visualisatie gaat maken in deze repo
- [x] Er zijn wel foto's over het concept, misschien dat je textueel nog kan uitleggen wat het concept inhoud?
- [x] Ik weet niet of je vanuit een voorbeeld hebt gewerkt, zo ja zet die er dan bij
- [x] Ik zou bij de subquestions/criteria nog neerzetten welke datasets en variabelen je gaat gebruiken per vraag.
- [x]  Misschien nog een schets uploaden van je visualisatie?
- [x] Er staat niet echt iets over wat je doet met lege/invalide data, zou ik nog wel kort beschrijven als je daar iets mee hebt gedaan zoals er buiten laten.
- Ik weet niet of filtering the data en datasets nog nodig is onder je foto's misschien dat je dit en je research questions samen kan voegen.

**Wiki:**
- [x]  Ik zou in ieder geval alles uit je wiki van functional programming overzetten naar deze wiki.
- [x]  Een pagina opzetten over hoe je data eruit zag na de fetch en hoe het eruit ziet na alle opschoning, korte beschrijving van wat de functies doen en hoe dit de data aanpast.
- [x]  Ik zou die vorige versie foto's over je concept gewoon in je wiki zetten omdat je nu niet echt weet welke foto nou de huidige versie is.
- [x] Een pagina opzetten over hoe het update pattern in D3 werkt en hoe jij dit hebt toegepast op je eigen project.
- [x] Je hebt vast genoeg geleerd over D3 aan de hand van Curran's tutorials, maak er een pagina voor aan in je wiki waar je in opschrijft wat je geleerd hebt en meegenomen hebt in je concept.

**Live Demo:**
- [x]  Misschien dat je de map op zichzelf al leeg kan laten zien zodat je weet met wat voor visualisatie je te maken hebt.
- [x] Data veranderd inderdaad door de input velden te veranderen.
- [x] Ik zou nog een state maken wanneer je geen resultaten krijgt dat je iets anders te zien krijgt, anders lijkt het alsof het nog aan het laden is.

**Comment by max-hauser** [comment]
8 uur later... Alles verwerkt!
